project:
  type: website
  output-dir: docs

website:
  title: "Carmen Hoyt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Resources.qmd
        text: Resources

format:
  html:
    theme:
      light: sandstone
      dark: slate
    css: styles.css
    toc: false
    page-layout: full


